# numpy basics

# ARRAY part 1

In [ ]:
mylist=[1,2,3,4,5,]  # in otherprogramming  it will produce error becasue of ,

In [4]:
mylist

[1, 2, 3, 4, 5]

In [5]:
type(mylist)

list

In [6]:
import numpy as np

In [7]:
arraylist=np.array(mylist)

In [8]:
arraylist

array([1, 2, 3, 4, 5])

In [46]:
arraylist.shape

(5,)

In [9]:
list2=[[1,2,3],[3,4,5],[6,7,8]]

In [10]:
list2

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [13]:
matrix=np.array(list2)

In [14]:
type(matrix)

numpy.ndarray

In [16]:
matrix

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [20]:
np.zeros

<function numpy.zeros>

In [21]:
np.zeros(2)

array([0., 0.])

In [23]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [24]:
type(0.0)

float

In [25]:
type(0.)

float

In [28]:
np.zeros((2,2))   # we can also put tuple in it

array([[0., 0.],
       [0., 0.]])

In [30]:
np.ones(2)

array([1., 1.])

In [31]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [32]:
np.ones((2,2)) +10

array([[11., 11.],
       [11., 11.]])

In [35]:
np.ones((2,2)) +np.ones((2,2)) +np.ones((2,2))  # this is not possible in python list that why we use numpy array

array([[3., 3.],
       [3., 3.]])

In [37]:
[1,2,3,4] *100  # it is not performing operation in it  but we want to multiply it

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,


In [38]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [39]:
len(np.linspace(0,10))   # its look  like defaulting is 50

50

In [40]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [41]:
len(np.linspace(0,10,3))

3

In [ ]:
# difference between arange and linspace 

#A : arange may  coantian starting numeber and  may not  contian ending number np.arange(0,10,3)  array([ 0,  3, 6 , 9])
#  : linspace alwasy contain stating and ending in output   np.linspace(0,10,3)    array([ 0.,  5., 10.])


# arange output is alwasys in interger not float
# linspace output is alwasys in float


In [42]:
np.eye(2)  # identity matrix 

array([[1., 0.],
       [0., 1.]])

In [43]:
np.eye(2) +np.eye(2)

array([[2., 0.],
       [0., 2.]])

# array part 2

In [ ]:
Random number contain 0 to 1  (iniform distibution)

In [47]:
np.random.rand(2,2)  # 0 to 1

array([[0.62629848, 0.86823521],
       [0.58309751, 0.55026424]])

In [48]:
np.random.randint(1,22)   # it give random number 1 is inclusive and 22 is excluding

15

In [49]:
np.random.randint(1,22),5

(5, 5)

In [51]:
np.random.randint(1,22,5)  # it will give 5 integer number
# value cahnge everytime in it

array([13,  8,  8, 17, 20])

In [55]:
#if you do not want to chage the random number then we can use seed in it
np.random.seed(42)
np.random.rand(4)  # it will not change the output  everytime i press enter in it

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [57]:
np.random.rand(4)  # value is chaged here but i didnt use seed in it

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [ ]:
# alwasy put 2 lines together


In [58]:
arr=np.arange(25)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
arr.shape

(25,)

In [61]:
arr.reshape(5,5)  # we convert one d into 2 d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
arr.max()   # it is not indicating index

24

In [64]:
arr.min()  # it is not indicating index

0

In [65]:
arr.mean()  # it is not indicating index

12.0

In [69]:
arr.argmax()  # it is showing index 24  , which is correct

24

In [68]:
arr.argmin()

0

In [71]:
arr.argmean()  # no function 

AttributeError: 'numpy.ndarray' object has no attribute 'argmean'

In [72]:
arr.dtype  # it shows the datatype 

dtype('int32')

In [73]:
type(arr)

numpy.ndarray

# indexing and selection in numpy

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr[0]

0

In [76]:
arr[0:12]  # slicing exclude 12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
arr[:5]

array([0, 1, 2, 3, 4])

In [78]:
arr[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [81]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [ ]:
 # that is all beacket idexng and selection for one dimensional rray

In [ ]:
broadcasing means *,-,/,+

In [82]:
arr +3 # something like tht

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27])

In [83]:
#whenever we slice the data nd assign to someother varibale  and we assigned some value in it ,
#that  cahnges also reflected in original array as well  (use copy function to neglect this error)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
arr_new=arr[0:4]

In [92]:
arr_new

array([0, 1, 2, 3])

In [93]:
arr_new[:]=99

In [94]:
type(arr_new
    )

numpy.ndarray

In [95]:
arr_new

array([99, 99, 99, 99])

In [96]:
arr  # it also efect original data as well 

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [98]:
 # always use copy function  to avoid the issue
   
arr=np.arange(23)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [100]:
arr_new=arr.copy()

In [101]:
arr_new[:]=99

In [102]:
arr_new

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99])

In [103]:
arr  # now it is working fine 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [109]:
# indexing on 2 d array
arr_2darray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [111]:
arr_2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr_2darray.shape

(3, 3)

In [114]:
arr_2darray.dtype

dtype('int32')

In [115]:
type(arr_2darray)

numpy.ndarray

In [116]:
arr_2darray[0]

array([1, 2, 3])

In [117]:
arr_2darray[0:2]    #  row to 1 row and excluding 2 row

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr_2darray[0:2,0]

array([1, 4])

In [120]:
arr_2darray[2:3]

array([[7, 8, 9]])

In [121]:
arr_2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
arr_2darray[0][0]

1

In [123]:
arr_2darray[2][2]

9

In [124]:
arr_2darray[2,2]

9

In [125]:
# indexing mean took one element and 
#selection mean bunch of number while purforming slicing

In [126]:
arr_2darray[:1,:1]  # it is showing correct value

array([[1]])

In [127]:
arr_2darray[:1,1:]

array([[2, 3]])

In [128]:
arr_2darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
arr_2darray[:2,:2]

array([[1, 2],
       [4, 5]])

In [130]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [133]:
arr>14

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True])

In [134]:
bool_arr=arr>14

In [135]:
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True])

In [136]:
arr[bool_arr]  # it will print only positive numbers in it

array([15, 16, 17, 18, 19, 20, 21, 22])

In [137]:
arr[bool_arr>14] # it si showing datatype

array([], dtype=int32)

In [139]:
# it is long process bt most people prefor to do thing thing in one line code
arr[arr>14]  # no need to create another variable

array([15, 16, 17, 18, 19, 20, 21, 22])

In [140]:
arr[arr==4]  # it is showing wheree arr is 4

array([4])

In [141]:
arr[arr <=4]  # conditional selection

array([0, 1, 2, 3, 4])

# numpy operation

In [142]:
arr=np.arange(0,12)

In [143]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
arr+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [145]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [146]:
arr /4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75])

In [147]:
arr ** 2  # square of a number

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [148]:
arr ^ 2   # i dont know ehat is doing surely it isnot squaring it

array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11,  8,  9], dtype=int32)

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
arr ** 3  # cube of element

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331], dtype=int32)

In [152]:
(arr+2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12,
       0.13])

In [153]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [154]:
arr_new=arr.copy()

In [155]:
arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [156]:
arr_new +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [158]:
#or
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [160]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [161]:
1/arr

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909])

In [162]:
arr/arr

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [163]:
#univeral function


In [164]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [165]:
np.log(arr)

C:\Users\Ajay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [166]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [167]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ])

In [168]:
#statistics in array


In [169]:
arr.sum()

66

In [170]:
arr.max()

11

In [171]:
arr.mean()  # all these results are in one dimenional aray

5.5

In [174]:
# lets see all the ouput in 2 da array

arr2d=np.array([[1,2,3],[4,5,6],[1,4,2]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 2]])

In [175]:
arr2d.sum(axis=0)  # sum of columns

array([ 6, 11, 11])

In [176]:
arr2d.sum(axis=1)   # sum of row

array([ 6, 15,  7])